### ISSUE TITLE
Allow to use specific version of Sympy

### ISSUE THREAD

**Issue by Tom-van-Woudenberg** [TeachBooks/Macaulays_method#7]
On this page: https://teachbooks.github.io/Macaulays_method/main/theses/borek_example.html I'd like to use a forked copy of sympy from within Sphinx-Thebe. Is this possible? @TeachBooks/escience-center-rses @DianaBanta ?

**Comment by BSchilperoort** [comment]
Hi Tom, pyodide uses "piplite" instead of pip, but this is not immediately clear.

piplite is built upon "micropip". micropip does support installing from URLS, [but only if it's a wheel](https://pyodide.org/en/latest/usage/loading-packages.html#installing-wheels-from-arbitrary-urls). So if you build a wheel from that fork you can install it.

**Comment by Tom-van-Woudenberg** [comment]
Thanks! That works! https://teachbooks.github.io/Macaulays_method/theses/borek_example.html!
I now remember that Robert did something similar with wheels before: https://gitlab.tudelft.nl/interactivetextbooks-citg/risk-and-reliability/-/blob/main/book/testing/test_pyvinecopulib.ipynb?ref_type=heads

**Comment by Tom-van-Woudenberg** [comment]
FYI, I added this to the manual: https://teachbooks.tudelft.nl/jupyter-book-manual/features/live_code.html#custom-packages
